//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sanguosha.Core.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.5.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool IsUsing386 {
            get {
                return ((bool)(this["IsUsing386"]));
            }
            set {
                this["IsUsing386"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>basic</string>
  <string>battle</string>
  <string>wind</string>
  <string>fire</string>
  <string>woods</string>
  <string>hills</string>
  <string>overknightfame11</string>
  <string>overknightfame12</string>
  <string>overknightfame13</string>
  <string>sp</string>
  <string>starsp</string>
  <string>assassin</string>
  <string>pk1v1</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection LoadSequence {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["LoadSequence"]));
            }
            set {
                this["LoadSequence"] = value;
            }
        }
    }
}
